name: PR commented
on:
  issue_comment:
    types:
      - created

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: vars
        with:
          script: |
            console.log("all")
            console.log(context)
            console.log(".github")
            console.log(context.payload.client_payload.github)
            console.log(".slash_command")
            console.log(context.payload.client_payload.slash_command)
            console.log("repo")
            console.log(context.repo)
            
            result = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.client_payload.github.payload.issue.number
            })
            
            core.setOutput("branch_name", result.data.head.ref); 
            core.setOutput("pr_number", context.payload.client_payload.github.payload.issue.number);
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          static-args: |
            branch_name=${{ steps.vars.outputs.branch_name }}
            pull_request_number=${{ steps.vars.outputs.pr_number }}
          commands: |
            help
            finish
