---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GET_TOKEN_APP_ID }}
          private-key: ${{ secrets.GET_TOKEN_PRIVATE_KEY }}
      # bootstrap-sha and release-as needs to be removed after first release
      - name: Release
        uses: google-github-actions/release-please-action@1ddb669c677d585663a83fc535edc428954c4aeb # ratchet:google-github-actions/release-please-action@v3
        with:
          release-type: python
          token: ${{ steps.app-token.outputs.token }}
          include-v-in-tag: false
          pull-request-header: ''
